title: "DevOps Portfolio"
description: "A professional portfolio showcasing DevOps skills and projects"
author: "Hari Prasad"
url: "https://harrythedevopsguy.com"
baseurl: ""  # The base URL of the site

# Build settings
markdown: kramdown
highlighter: rouge

# Theme and Plugins
theme: jekyll-theme-minimal
plugins:
  - jekyll-fontawesome
  - jekyll-seo-tag
