title: "Harry's DevOps Portfolio"
description: "A Senior DevOps Engineer with over 11 years of experience"
url: "https://harrythedevopsguy.github.io"
baseurl: "/cv/"
author: Harry

paginate: 5
paginate_path: "/blog/page:num"