title: "Harry's DevOps Portfolio"
description: "A Senior DevOps Engineer with over 11 years of experience"
url: "https://example.com"
baseurl: "/"

# Markdown options
markdown: kramdown

# Collections for custom layouts
collections:
  resume:
    output: true
  blog:
    output: true

# Plugins (Optional)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
