title: Hari Prasad's DevOps Portfolio
description: A senior DevOps engineer’s portfolio showcasing experience, skills, and projects.
url: "https://harrythedevopsguy.github.io"
author:
  name: Hari Prasad
  email: HarryTheDevOpsGuy@gmail.com
  github: https://github.com/HarryTheDevOpsGuy
  linkedin: https://linkedin.com/in/HarryTheDevOpsGuy
  location: "City, State, Country"
